# Generated by Django 5.2.1 on 2025-05-13 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Capitulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('numero', models.IntegerField()),
                ('link', models.URLField()),
                ('percentual_completo', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField()),
                ('capitulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercicios', to='capitulos.capitulo')),
            ],
        ),
        migrations.CreateModel(
            name='ExercicioUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dificuldade', models.CharField(choices=[('Muito Fácil', 'Muito Facil'), ('Fácil', 'Facil'), ('Médio', 'Medio'), ('Difícil', 'Dificil'), ('Muito Difícil', 'Muito Dificil')], max_length=20)),
                ('nota', models.IntegerField()),
                ('feito', models.BooleanField(default=False)),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercicios_usuario', to='capitulos.exercicio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercicios_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('exercicio', 'usuario'), name='unique_exercicio_usuario')],
            },
        ),
    ]
