# Generated by Django 5.2.1 on 2025-05-13 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capitulos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capitulo',
            name='percentual_completo',
        ),
    ]
