# Generated by Django 5.2.1 on 2025-05-13 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capitulos', '0002_remove_capitulo_percentual_completo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciciousuario',
            name='dificuldade',
            field=models.CharField(blank=True, choices=[('Muito Fácil', 'Muito Facil'), ('Fácil', 'Facil'), ('Médio', 'Medio'), ('Difícil', 'Dificil'), ('Muito Difícil', 'Muito Dificil')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='exerciciousuario',
            name='nota',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
