# Generated by Django 5.2.1 on 2025-05-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capitulos', '0003_alter_exerciciousuario_dificuldade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercicio',
            name='nome',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
