# Generated by Django 5.2.1 on 2025-05-17 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capitulos', '0004_exercicio_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciciousuario',
            name='nota',
            field=models.CharField(blank=True, choices=[(0, 'Zero'), (1, 'Um'), (2, 'Dois'), (3, 'Tres'), (4, 'Quatro')], max_length=20, null=True),
        ),
    ]
