# Generated by Django 5.2.1 on 2025-05-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capitulos', '0006_alter_exerciciousuario_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciciousuario',
            name='dificuldade',
            field=models.IntegerField(blank=True, choices=[(0, 'Zero'), (1, 'Um'), (2, 'Dois'), (3, 'Tres'), (4, 'Quatro')], null=True),
        ),
    ]
