# Generated by Django 5.2.1 on 2025-05-31 17:17

import prose.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capitulos', '0007_alter_exerciciousuario_dificuldade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercicio',
            name='enunciado',
            field=prose.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='exerciciousuario',
            name='dificuldade',
            field=models.IntegerField(blank=True, choices=[(0, 'Muito Ruim'), (1, 'Ruim'), (2, 'Mais Ou Menos'), (3, 'Bom'), (4, 'Muito Bom')], null=True),
        ),
        migrations.AlterField(
            model_name='exerciciousuario',
            name='nota',
            field=models.IntegerField(blank=True, choices=[(0, 'Muito Ruim'), (1, 'Ruim'), (2, 'Mais Ou Menos'), (3, 'Bom'), (4, 'Muito Bom')], null=True),
        ),
    ]
