# Generated by Django 5.2.1 on 2025-06-25 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capitulos', '0008_alter_exercicio_enunciado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capitulo',
            name='link',
        ),
        migrations.AddField(
            model_name='exercicio',
            name='link',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
