# Generated by Django 5.2.1 on 2025-06-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capitulos', '0009_remove_capitulo_link_exercicio_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercicio',
            name='ordem',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
