# Generated by Django 5.2.1 on 2025-06-29 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capitulos', '0010_exercicio_ordem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercicio',
            options={'ordering': ['ordem']},
        ),
        migrations.AddConstraint(
            model_name='exercicio',
            constraint=models.UniqueConstraint(fields=('capitulo', 'ordem'), name='unique_capitulo_ordem'),
        ),
    ]
