# Generated by Django 5.2.1 on 2025-06-30 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capitulos', '0011_alter_exercicio_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciciousuario',
            name='dificuldade',
            field=models.IntegerField(blank=True, choices=[(0, 'Muito Ruim'), (1, 'Ruim'), (2, 'Mais Ou Menos'), (3, 'Bom'), (4, 'Muito Bom')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='exerciciousuario',
            name='nota',
            field=models.IntegerField(blank=True, choices=[(0, 'Muito Ruim'), (1, 'Ruim'), (2, 'Mais Ou Menos'), (3, 'Bom'), (4, 'Muito Bom')], default=4, null=True),
        ),
    ]
