# Generated by Django 5.2.1 on 2025-09-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capitulos', '0013_alter_exercicio_ordem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercicio',
            name='ordem',
            field=models.IntegerField(default=9963),
        ),
    ]
